### PR TITLE
fix bug

### PR DESCRIPTION
**Pull request by Edison-Yeah**
When a transaction requiring a large amount of collateral is blocked, transactions requiring only a small amount of collateral from the same client submitted with the transaction are blocked.

### CODE REVIEW

**Review by vyzo — COMMENTED** [review]
this is consensus breaking and the next upgrade will run the fvm, so this bug should be fixed in bultin-actors repo, if present.

**Review by Stebalien — COMMENTED** [review]
This fix looks correct to me. cc @jennijuju because it's consensus critical.

**Comment by anorth** [comment]
Please add a test demonstrating the issue fixed

**Review by ZenGround0 — COMMENTED** [review]
LGTM
As others have pointed out this needs test ~and a corresponding change in builtin actors~ to make it into the next upgrade.
I would also appreciate more separation between names beyond swapping client/provider and total which makes things easy to confuse.  `totalXLockupTmp`, `totalXLockupNew`, `totalXLockupAcc` etc.

**Comment by arajasek** [comment]
Thanks for the fix! I've transported this to the new Rust-based builtin-actors in https://github.com/filecoin-project/builtin-actors/pull/414, along with some tests!

**Comment by arajasek** [comment]
I don't have an opinion on whether or not we should merge this PR, or just close it since this repo is no longer "specs-actors".

**Comment by ZenGround0** [comment]
Archiving repo

**Pull request closed without merging**
