### PR TITLE
Skip miner for miners who's proving periods haven't started

### PR DESCRIPTION
**Pull request by Stebalien**
The migration logic assumes that proving periods are never set in the future, and miners that haven't started their first proving period will not have experienced any faults that need correcting.

### CODE REVIEW

**Comment by Stebalien** [comment]
Depends on https://github.com/filecoin-project/specs-actors/pull/1209

**Comment by Stebalien** [comment]
So, the question is, is this OK? I think it is, but I'm not sure if there's an edge-case I'm missing.

**Comment by ZenGround0** [comment]
I'm not sure if its impossible to precommit, provecommit, cc upgrade, and fault before the proving period starts but likely it is.  It also should be impossible to expire precommits before the proving period starts.  I'll take a look tomorrow.

Even if it is technically possible this should probably be good enough since we are not expecting cc upgrades right now on testnet.  If there is a theoretical loophole we could also ask miners to hold off on cc upgrades a day or so before the launch.

**Comment by Stebalien** [comment]
> fault before the proving period starts but likely it is.

You would have had to have submitted an explicit fault, which lotus won't do until you start proving, I think. But it may technically be possible.

Note: this isn't the only fix. We just need to make sure we don't (a) change the deadline/proving period or (b) reschedule cron in this case.

**Review by ZenGround0 — APPROVED** [review]
Should be fine.  If I have time I want to double check this for safety

**Pull request merged**
