### PR TITLE
Adjust code for subtle change in go-multihash 0.0.15

### PR DESCRIPTION
**Pull request by ribasushi**
go-multihash is now wrapping the returned error, so the check  in the test lib requires an `errors.Is`
https://github.com/multiformats/go-multihash/blob/v0.0.15/core/registry.go#L58-L60

cc @warpfork @mvdan

### CODE REVIEW

**Review by mvdan — APPROVED** [review]

**Review by Stebalien — APPROVED** [review]

**Comment by Stebalien** [comment]
This updates a dependency, so please don't merge until we've cut a v6 branch.

**Comment by Stebalien** [comment]
Pushed to chore/upgrade_go-multihash

**Review by marten-seemann — APPROVED** [review]

**Comment by ribasushi** [comment]
> This updates a dependency, so please don't merge until we've cut a v6 branch.

@Stebalien I just realized I do not need to do any of the version bumps. The diff in this PR at the time of writing is sufficient to allow `lotus` itself to jump to `go-multihash v0.0.15`

**Review by Stebalien — APPROVED** [review]

**Comment by Stebalien** [comment]
Merging because this is a testing only chanage.

**Review by 0racl3z — COMMENTED** [review]
Thanks!

**Pull request merged**
