### PR TITLE
add method to fetch available multisig balance

### PR DESCRIPTION
**Pull request by whyrusleeping**
This is a quick PR to prompt the discussion:
This is a very useful piece of information that people will want to query often. It makes sense to me to include it as a method here. However, I also had a conversation with @anorth about similar things, where we said it also makes sense to make these be methods on the state object, and that queries could load actor state into that struct and call the methods on the state objects.

Happy with whatever outcome, let's use this PR as a discussion space to all come to agreement on the desired approach.

### CODE REVIEW

**Comment by whyrusleeping** [comment]
Additional context here:
I have an ask for a way to get this information from a group that we are working with. In lotus we have a CLI interface for the multisig, but we don't have any dedicated API methods. You can get this information for yourself through the API, but you would then have to implement all the mathematical logic clientside, which is suboptimal. If we add this as a method on the actor, then you can use the StateCall api to get the data you need.

**Comment by anorth** [comment]
cc @acruikshank for the discussion

**Comment by anorth** [comment]
My preferred approach would be to have queries and arithmetic like this as methods on the state object, and implementations provide access to the state object without involving the VM, method dispatch, or any actor code. Most state object methods probably need to be exported for external access.

The exported methods on the actors themselves would probably be limited to VM-dispatchable methods.

**Comment by whyrusleeping** [comment]
@anorth the one problem i have with that approach (which is not necessarily a deal breaker) is that that logic is not accessible for anyone not writing go. For example, people interacting with lotus over the rpc api

**Comment by acruikshank** [comment]
@whyrusleeping it seems this approach would just involve adding these state objects to the RPC layer. That would probably mean a slightly larger API, but individual queries would have simpler, more targeted signatures.

**Comment by whyrusleeping** [comment]
@acruikshank I don't see how this solves the problem, unless youre saying "make special api calls for each of these state object methods". Which feels rather unsustainable to me, but on the other side, the same thing applies to adding more actor methods.

**Comment by acruikshank** [comment]
@whyrusleeping I was assuming that would would have an endpoint for each of these methods, and also assuming that wouldn't be more difficult than exposing an actor method. I can see how that second assumption may be incorrect. I only have a slight preference for actor state methods over actor methods because they'll be cleaner to use in gfc. I would like to avoid having actor methods that do nothing but wrap actor state methods, but even that isn't the end of the world.

**Comment by anorth** [comment]
We have been operating without these methods for a while now and it seems ok. I'm going to close the PR/discussion now, but welcome re-opening it if more info arises.

**Pull request closed without merging**
