### PR TITLE
Migration to remove existing miners with invalid window post proof types

### PR DESCRIPTION
**Pull request by laudiacay**
see #1474

### CODE REVIEW

**Comment by ZenGround0** [comment]
Random thought, I think we need to remove these miners from init actor state, not sure if this PR does that yet.

**Comment by laudiacay** [comment]
It does not. Aaaaaaaaaaaaaagh. I’ll do this tomorrow.

**Comment by Stebalien** [comment]
@ZenGround0 are you sure? I'd expect us to mimic the `DeleteActor` syscall, which _doesn't_ touch the init state. I don't think we currently garbage collect the init actor at all.

**Comment by ZenGround0** [comment]
Ah in that case maybe not.

**Pull request closed without merging**
